# Usar una imagen base oficial de Golang para compilar la aplicación
FROM golang:1.23-alpine AS build

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos go.mod y go.sum
COPY go.mod go.sum ./

# Descargar las dependencias
RUN go mod download

# Copiar los archivos del proyecto al directorio de trabajo del contenedor
COPY . .

# Compilar la aplicación
RUN go build -o main ./cmd/Comentario-pf/main.go

# Usar una imagen base más ligera para el contenedor final
FROM alpine:latest

# Establecer el directorio de trabajo
WORKDIR /root/

# Copiar el binario de la aplicación desde la imagen de compilación
COPY --from=build /app/main .

# Copiar el archivo .env si es necesario
COPY --from=build /app/cmd/Comentario-pf/.env .

# Definir el punto de entrada para la aplicación CLI
ENTRYPOINT ["./main"]
